/*
 * EnvironmentDefs.h
 *
 *  Created on: 19 mars 2020
 *      Author: ebeuque
 */

#ifndef SRC_ENVIRONMENT_ENVIRONMENTDEFS_H_
#define SRC_ENVIRONMENT_ENVIRONMENTDEFS_H_

#define VE_FILE "ve.env"

#define VE_VAR_TARGET_PLATFORM "TARGET_PLATFORM"
#define VE_VAR_GIT "GIT"
#define VE_VAR_HG "HG"
#define VE_VAR_SVN "SVN"
#define VE_VAR_MAKE "MAKE"
#define VE_VAR_RSYNC "RSYNC"
#define VE_VAR_COMPILER "COMPILER"
#define VE_VAR_CROSS_COMPIL_PREFIX "CROSS_COMPIL_PREFIX"
#define VE_VAR_PKG_CONFIG_LIBDIR "PKG_CONFIG_LIBDIR"
#define VE_VAR_TAR "TAR"
#define VE_VAR_WGET "WGET"

#endif /* SRC_ENVIRONMENT_ENVIRONMENTDEFS_H_ */
